spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tradeup
    username: tradeup
    password: tradeup
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none